vpc_cidr_block    = "10.0.0.0/16"
subnet_cidr_block = "10.0.10.0/24"
availability_zone = "eu-west-1a"
env_prefix        = "dev-root"
instance_type     = "t2.micro"
aws_region        = "eu-west-1"